package com.nt.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
@WebServlet("/about2url")
public class AboutServlet extends HttpServlet {
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {
		PrintWriter  pw=null;
		pw=res.getWriter();
		String sno=req.getParameter("eno");
		int eno=Integer.parseInt(sno);
		String sname=req.getParameter("ename");
		res.setContentType("text/html");
		pw.println("<h1 style='color:red'>Out put generated by destination Servlet</h1>");
		pw.println("<h1 style='color:red;text-align:center'>Employe No::"+eno+"</h1>");
		pw.println("<h1 style='color:red;text-align:center'>Employe Name::"+sname+"</h1>");
		pw.println("<a href='http://localhost:3030/AboutInfo1/index.html'>Home</a>");
	}
	@Override
	public void doPost(HttpServletRequest req, HttpServletResponse res) throws ServletException, IOException {

	    doGet(req,res);
	}

}
